-define(LISTEN_PORT, "8910").
-define(INTERNAL_PATH, "/file-internal").
-define(TMP_PATH, "/tmp/idp_proxy/tmp").
-define(DOC_ROOT, "/tmp/idp_proxy").
-define(S3CMD, "~/bin/s3sync/s3cmd.rb").
-define(S3BUCKET, "your-bucket-name").
-define(S3PREFIX, "a/b/c/d/e/f").
